// Maps team names (as they appear from football-data.org or manual entry)
// to ISO 3166-1 alpha-2 codes, used to render flags via flagcdn.com.
// This avoids relying on emoji flags, which render inconsistently
// (especially on Windows Chrome, where many show as blank/boxes).

const TEAM_TO_ISO = {
  // Confirmed World Cup 2026 qualifiers + common name variants
  mexico: 'mx',
  canada: 'ca',
  'united states': 'us',
  usa: 'us',
  argentina: 'ar',
  brazil: 'br',
  france: 'fr',
  england: 'gb-eng',
  spain: 'es',
  germany: 'de',
  portugal: 'pt',
  netherlands: 'nl',
  belgium: 'be',
  italy: 'it',
  croatia: 'hr',
  switzerland: 'ch',
  denmark: 'dk',
  uruguay: 'uy',
  colombia: 'co',
  ecuador: 'ec',
  japan: 'jp',
  'south korea': 'kr',
  korea: 'kr',
  'korea republic': 'kr',
  iran: 'ir',
  'saudi arabia': 'sa',
  qatar: 'qa',
  australia: 'au',
  'new zealand': 'nz',
  morocco: 'ma',
  senegal: 'sn',
  tunisia: 'tn',
  ghana: 'gh',
  cameroon: 'cm',
  nigeria: 'ng',
  egypt: 'eg',
  algeria: 'dz',
  'ivory coast': 'ci',
  "cote d'ivoire": 'ci',
  'south africa': 'za',
  panama: 'pa',
  'costa rica': 'cr',
  jamaica: 'jm',
  honduras: 'hn',
  haiti: 'ht',
  curacao: 'cw',
  paraguay: 'py',
  bolivia: 'bo',
  venezuela: 've',
  poland: 'pl',
  ukraine: 'ua',
  serbia: 'rs',
  wales: 'gb-wls',
  scotland: 'gb-sct',
  norway: 'no',
  sweden: 'se',
  austria: 'at',
  czechia: 'cz',
  'czech republic': 'cz',
  slovakia: 'sk',
  slovenia: 'si',
  'bosnia-herzegovina': 'ba',
  'bosnia and herzegovina': 'ba',
  bosnia: 'ba',
  turkey: 'tr',
  türkiye: 'tr',
  greece: 'gr',
  finland: 'fi',
  iceland: 'is',
  hungary: 'hu',
  romania: 'ro',
  russia: 'ru',
  china: 'cn',
  india: 'in',
  uzbekistan: 'uz',
  jordan: 'jo',
  iraq: 'iq',
  'cape verde': 'cv',
  'dr congo': 'cd',
  congo: 'cg',
  uganda: 'ug',
  gabon: 'ga',
  benin: 'bj',
  mali: 'ml',
  guinea: 'gn',
  zambia: 'zm',
  mozambique: 'mz',
  comoros: 'km',
  'new caledonia': 'nc',
  fiji: 'fj',
  tahiti: 'pf',
  'papua new guinea': 'pg',
  'solomon islands': 'sb',
  vanuatu: 'vu',
  suriname: 'sr',
  guatemala: 'gt',
  'el salvador': 'sv',
  'trinidad and tobago': 'tt',
  'trinidad & tobago': 'tt',
  'puerto rico': 'pr',
  bermuda: 'bm',
};

/**
 * Resolve a team name to a flagcdn.com flag image URL.
 * Falls back to a generic placeholder (a blank flag icon) if no match found.
 */
export function getFlagUrl(teamName, size = 'w80') {
  if (!teamName) return null;
  const key = teamName.trim().toLowerCase();
  const iso = TEAM_TO_ISO[key];
  if (!iso) return null;
  return `https://flagcdn.com/${size}/${iso}.png`;
}

export default TEAM_TO_ISO;
